const Projects = [
    {
        Id: '1',
        pImg:
        //'https://images.pexels.com/photos/3018845/pexels-photo-3018845.jpeg?cs=srgb&dl=pexels-jhong-pascua-3018845.jpg&fm=jpg',
        '/images/my/fot-1.jpg',
        slug:'Water-Line-Repair',
        subTitle:'Plumbing',
        title: 'Water Line Repair',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '2',
        pImg:
        //'https://beautysociety.com/wp-content/uploads/2023/05/MULTIPLE-PRODUCTS-scaled.jpg',
        '/images/my/fot-2.jpg',
        slug:'Basement-Plumbing',
        subTitle:'Plumbing',
        title: 'Basement Plumbing',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '3',
        pImg:
        //'https://images.ctfassets.net/c9o4jciad99f/3bjj1BTkCpSwm69MS3hIdY/b159ef5fd78fb175d68deb6e7e9325ab/allure_LLM_Square.jpg?w=512&fm=jpg',
        '/images/my/fot-3.jpg',
        slug:'Remodeling-Service',
        subTitle:'Plumbing',
        title: 'Remodeling Service',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '4',
        pImg:
        //'https://assets.boots.com/content/dam/boots/shop-by-department/beauty-and-skincare/2022-2023/9a/premium-beauty/9a_PremiumBeauty_50_Kylie_Kylash_Supplied.dam.ts%3D1679408579379.jpg',
        '/images/my/fot-4.jpg',
        slug:'Water-Line-Repairs',
        subTitle:'Plumbing',
        title: 'Water Line Repair',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '5',
        pImg:
        //'https://productimages.hepsiburada.net/s/312/375/110000305713871.jpg',
        '/images/my/fot-5.jpg',
        slug:'Kitchen-Plumbing',
        subTitle:'Plumbing',
        title: 'Kitchen Plumbing',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '6',
        pImg:
        //'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHML2mwGxVS3zzFarFvlFtW8kkdcY0GKzeRg&usqp=CAU',
        '/images/my/fot-6.jpg',
        slug:'Gas-Line-Services',
        subTitle:'Plumbing',
        title: 'Gas Line Services',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '7',
        pImg:'/images/projects/img-6.jpg',
        slug:'Kitchen-Plumber',
        subTitle:'Plumbing',
        title: 'Kitchen Plumbing',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '8',
        pImg:'/images/projects/img-10.jpg',
        slug:'Basement-Plumber',
        subTitle:'Plumbing',
        title: 'Basement Plumbing',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
    {
        Id: '9',
        pImg:'/images/projects/img-11.jpg',
        slug:'Remodeling-Services',
        subTitle:'Plumbing',
        title: 'Remodeling Service',
        description:'We are certified company. We provide best cleaning projects for you and your company Home projects and your Car.',
        spImg1:'/images/project-single/2.jpg',
        spImg2:'/images/project-single/3.jpg',
    },
]
export default Projects;